version: 2

defaults: &defaults
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.7
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      # - image: circleci/postgres:9.4.12-alpine
      #   environment:
      #     POSTGRES_USER: root
      #     POSTGRES_DB: circle_test
jobs:
  build:
    <<: *defaults
    working_directory: /go/src/github.com/joincivil/go-common
    environment:
    steps:
      - run:
          name: Local docker sudo
          command: |
            if [[ $CIRCLE_BUILD_NUM -gt 0 ]]; then
              echo "This is not a local build. Disabling sudo for docker"
              touch ~/sudo
            else
              echo "This is a local build. Enabling sudo for docker"
              echo sudo > ~/sudo
            fi
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
           name: Setting up tools
           command: make check-go-env
      # - run:
      #     name: Waiting for Postgres to be ready
      #     command: |
      #       for i in `seq 1 10`;
      #       do
      #         nc -z localhost 5432 && echo Success && exit 0
      #         echo -n .
      #         sleep 1
      #       done
      #       echo Failed waiting for Postgres && exit 1
      - run:
          name: Building code
          command: make build
      - persist_to_workspace:
          root: ./
          paths:
            - build
            - pkg
            - Makefile
            - vendor
            - scripts
            - cmd
            - .gometalinter.json

  lint:
    <<: *defaults
    working_directory: /go/src/github.com/joincivil/go-common
    environment:
    steps:
        - attach_workspace:
            at: ./
        - run:
           name: Setting up tools
           command: make install-linter
        - run:
            name: Run linter
            command: make lint

  test:
    <<: *defaults
    working_directory: /go/src/github.com/joincivil/go-common
    environment:
    steps:
        - attach_workspace:
            at: ./
        - run:
            name: Run unit tests
            # environment:
            #    DB_URL: "postgres://root@localhost:5432/circle_test?sslmode=disable"
            #    DB_MIGRATIONS: /go/src/github.com/joincivil/go-common/migrations
            command: |
               make test


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build